# Generated by Django 3.1.5 on 2021-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinelot',
            name='status',
            field=models.CharField(choices=[('produced', 'produced'), ('atDistrict', 'atDistrict'), ('atCenter', 'atCenter'), ('consumed', 'consumed')], default='produced', max_length=11),
        ),
    ]
