# Generated by Django 3.1.5 on 2021-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinelot',
            name='departureTimestamp',
            field=models.DateTimeField(),
        ),
    ]
