# Generated by Django 3.0.7 on 2021-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0002_auto_20210329_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinelot',
            name='status',
            field=models.CharField(choices=[('produced', 'produced'), ('atDistrict', 'atDistrict'), ('atCenter', 'atCenter'), ('consumed', 'consumed')], default='produced', max_length=10),
        ),
    ]
