# Generated by Django 3.1.5 on 2021-03-28 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0005_auto_20210328_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscontrollistcenter',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_list_center', to='vaccine_app.center'),
        ),
        migrations.AlterField(
            model_name='accesscontrollistdistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_control_list_district', to='vaccine_app.district'),
        ),
    ]
