# Generated by Django 3.1.5 on 2021-03-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0006_auto_20210328_1313'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accesscontrollistcenter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='accesscontrollistdistrict',
            unique_together=set(),
        ),
    ]
